share/urls.py
from django.conf.urls import patterns, url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'sharewall.ru administration'
admin.site.site_title = 'fruitbag.ru administration'

#urlpatterns = patterns('',
    #(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
#)

urlpatterns = [
    url(r'^', include('landing.urls')),
    url(r'^share-admin/', admin.site.urls),
    url(r'^buttons-constructor/', include('buttons_constructor.urls')),
    url(r'^cabinet-webmaster/', include('cabinet_webmaster.urls')),
    url(r'^webmaster-area/', include('webmaster_area.urls')),
]# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += patterns('', 
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT})
)

webmaster_area/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.WebmasterAreaIndexView.as_view(), name='webmaster-area-index'),
    url(r'^statistic/$', views.statistic, name='webmaster-area-statistic'),
    url(r'^create/$', views.create, name='webmaster-area-create'),
    url(r'^update/(?P<pk>[0-9]+)/$', views.update, name='webmaster-area-update'),
    url(r'^delete/(?P<pk>[0-9]+)/$', views.delete, name='webmaster-area-delete'),
    url(r'^detail/(?P<name>[^/]+)/$', views.detail, name='webmaster-area-detail'),
    url(r'^detail-social/(?P<name>[^/]+)/$', views.detailsocial, name='webmaster-area-detail-social'),
    url(r'^detail-advert/(?P<name>[^/]+)/$', views.detailadvert, name='webmaster-area-detail-advert'),
    url(r'^detail-main/$', views.detailmain, name='webmaster-area-detail-main'),
    url(r'^setcounter/$', views.setcounter, name='webmaster-area-setcounter'),
    url(r'^getconfig/$', views.getconfig, name='webmaster-area-getconfig'),
    url(r'^checkconfig/$', views.checkconfig, name='webmaster-area-checkconfig'),
    url(r'^getadvert/(?P<cook>[^/]+)/$', views.getAdvert, name='webmaster-area-getAdvert'),
    url(r'^detail-error/$', views.detail_error, name='webmaster-area-detail-error'),
    url(r'^thu-may/555/update-server/$', views.updateServer, name='webmaster-area-update-server'),
    url(r'^delete-category/$', views.deleteCategory, name='webmaster-area-delete-category'),
    url(r'^add-category/$', views.addCategory, name='webmaster-area-add-category'),
    url(r'^faq/$', views.faq, name='webmaster-area-faq'),
]

webmaster_area/models.py
from urllib.parse import urlparse
from django.db import models
from buttons_constructor.models import ButtonsConstructorModel, SocialNetworks
from cabinet_webmaster.models import CabinetWebmasterModel

class Faq(models.Model):
    header = models.CharField("header", max_length=200, null=False, blank=False, default=" ")
    text = models.TextField("text", blank=True, default=" ")

class AreaCategory(models.Model):
    name = models.CharField("name", max_length=200)
    db_table = "AreaCategory"

    def __str__(self):
        return str("Category name: %s" % self.name)

class WebmasterAreaModel(models.Model):
    buttons_constructor = models.ForeignKey(ButtonsConstructorModel, on_delete=models.CASCADE, blank=True, null=True, verbose_name='related_buttons_constructor', related_name='webmaster_area')

    name_area = models.CharField(max_length=200, default='name area', verbose_name='name area')
    url = models.URLField('url', null=False, blank=False, default='')

    NORMAL = 'NORM'
    ADULT = 'ADUL'
    AD_TYPES_CHOICES=(
        (NORMAL,'Нормальный'),
        (ADULT,'Для взрослых'),
    )
    ad_type = models.CharField("ad_type", max_length=4, choices=AD_TYPES_CHOICES, default=NORMAL)

    area_cat_list = AreaCategory.objects.all()
    AREA_CAT_DEFAULT = ''
    for a in area_cat_list:
        if not a.name in AREA_CAT_DEFAULT:
            AREA_CAT_DEFAULT += a.name + ','
    AREA_CAT_DEFAULT = AREA_CAT_DEFAULT[:-1]
    area_category = models.CharField('area_category', max_length=600, default=AREA_CAT_DEFAULT)

    sn_list = SocialNetworks.objects.all()
    SOCIAL_DEFAULT = ''
    COUNTER_DEFAULT = ''
    for s in sn_list:
        if not s.shortcut in SOCIAL_DEFAULT:
            SOCIAL_DEFAULT += s.shortcut + ','
            COUNTER_DEFAULT += '0,'
    SOCIAL_DEFAULT = SOCIAL_DEFAULT[:-1]
    COUNTER_DEFAULT = COUNTER_DEFAULT[:-1]

    total_social_counter = models.CharField("total social counter(%s)"%SOCIAL_DEFAULT, max_length=300, default=COUNTER_DEFAULT)
    total_share_counter = models.CharField("total share counter(%s)"%SOCIAL_DEFAULT, max_length=300, default=COUNTER_DEFAULT)

    db_table = 'WebmasterAreaModel'
    
    def __str__(self):
        return str("Area name: %s" % self.name_area + ", area url: %s" % self.url + " <<== %s" % self.buttons_constructor)

    #TODO:log to log_table
    def save(self, *args, **kwargs):
        if 'http' not in self.url:
            self.url = 'http://'+self.url
        host = urlparse(self.url)
        if not host.netloc:
            return
        self.url = host.netloc
        super(WebmasterAreaModel, self).save(*args, **kwargs)
        
class AreaToday(models.Model):
    webmaster_area = models.ForeignKey(WebmasterAreaModel, on_delete=models.SET_NULL, blank=True, null=True, verbose_name='related_webmaster_area', related_name='area_today')

    date = models.DateField('date', auto_now_add=True)

    sn_list = SocialNetworks.objects.all()

    SOCIAL_DEFAULT = ''
    COUNTER_DEFAULT = ''
    for s in sn_list:
        if not s.shortcut in SOCIAL_DEFAULT:
            SOCIAL_DEFAULT += s.shortcut + ','
            COUNTER_DEFAULT += '0,'
    SOCIAL_DEFAULT = SOCIAL_DEFAULT[:-1]
    COUNTER_DEFAULT = COUNTER_DEFAULT[:-1]

    today_share_counter = models.CharField("today share counter(%s)"%SOCIAL_DEFAULT, max_length=300, default=COUNTER_DEFAULT)
    today_social_counter = models.CharField("today social counter(%s)"%SOCIAL_DEFAULT, max_length=300, default=COUNTER_DEFAULT)
    # Adv
    today_show_counter = models.IntegerField('today show counter', default=0)
    today_click_counter = models.IntegerField('today click counter', default=0)
    today_money = models.FloatField("today money in rub", default=0.0)
    
    db_table = 'AreaToday'
    
    def __str__(self):
        if self.webmaster_area:
            return str('Date: %s ' % self.date.strftime('%d/%m/%Y') + '; <<== %s' % self.webmaster_area)
        else:
            return str("Without webmaster_area")

class PageDetail(models.Model):
    webmaster_area = models.ForeignKey(WebmasterAreaModel, on_delete=models.CASCADE, blank=True, null=True, verbose_name='related webmaster_area', related_name='page_detail')

    title = models.CharField(max_length=512, default='', verbose_name='page title')
    url = models.URLField('page url', null=False, blank=False, default='')

    sn_list = SocialNetworks.objects.all()

    SOCIAL_DEFAULT = ''
    COUNTER_DEFAULT = ''

    for s in sn_list:
        if not s.shortcut in SOCIAL_DEFAULT:
            SOCIAL_DEFAULT += s.shortcut + ','
            COUNTER_DEFAULT += '0,'

    SOCIAL_DEFAULT = SOCIAL_DEFAULT[:-1]
    COUNTER_DEFAULT = COUNTER_DEFAULT[:-1]

    total_social_counter = models.CharField("total social counter(%s)"%SOCIAL_DEFAULT, max_length=300, default=COUNTER_DEFAULT)
    total_share_counter = models.CharField("total share counter(%s)"%SOCIAL_DEFAULT, max_length=300, default=COUNTER_DEFAULT)

    db_table = 'PageDetail'

    def __str__(self):
        return str(self.title + ' - ') + self.url

class PageToday(models.Model):
    page_detail = models.ForeignKey(PageDetail, on_delete=models.SET_NULL, blank=True, null=True, verbose_name='related_page_detail', related_name='page_today')

    date = models.DateField('date', auto_now_add=True)

    sn_list = SocialNetworks.objects.all()
    SOCIAL_DEFAULT = ''
    COUNTER_DEFAULT = ''
    for s in sn_list:
        if not s.shortcut in SOCIAL_DEFAULT:
            SOCIAL_DEFAULT += s.shortcut + ','
            COUNTER_DEFAULT += '0,'
    SOCIAL_DEFAULT = SOCIAL_DEFAULT[:-1]
    COUNTER_DEFAULT = COUNTER_DEFAULT[:-1]

    today_share_counter = models.CharField("today share counter(%s)"%SOCIAL_DEFAULT, max_length=300, default=COUNTER_DEFAULT)
    today_social_counter = models.CharField("today social counter(%s)"%SOCIAL_DEFAULT, max_length=300, default=COUNTER_DEFAULT)
    # Adv
    today_show_counter = models.IntegerField('today show counter', default=0)
    today_click_counter = models.IntegerField('today click counter', default=0)
    today_money = models.FloatField("today money in rub", default=0.0)

    # Default
    default_today_share_counter = models.CharField("default today share counter(%s)"%SOCIAL_DEFAULT, max_length=300, default=COUNTER_DEFAULT)
    default_today_social_counter = models.CharField("default today social counter(%s)"%SOCIAL_DEFAULT, max_length=300, default=COUNTER_DEFAULT)
    # Adv
    default_today_show_counter = models.IntegerField('default today show counter', default=0)
    default_today_click_counter = models.IntegerField('default today click counter', default=0)
    default_today_money = models.FloatField("default today money in rub", default=0.0)

    def getOddShare(self):
        r = ''

        for i1, i2 in zip(self.today_share_counter.split(','), self.default_today_share_counter.split(',')):
            if int(i1)-int(i2) < 0:
                r += str(0) + ','

            else:
                r += str(int(i1)-int(i2)) + ','
            #r += str(int(i1)-int(i2)) + ','

        r = r[:-1]
        return str(r)

    getOddShare.allow_tags = True

    def getOddSocial(self):
        r = ''

        for i1, i2 in zip(self.today_social_counter.split(','), self.default_today_social_counter.split(',')):
            if int(i1)-int(i2) < 0:
                r += str(0) + ','

            else:
                r += str(int(i1)-int(i2)) + ','
            #r += str(int(i1)-int(i2)) + ','

        r = r[:-1]
        return str(r)

    getOddSocial.allow_tags = True

    db_table = 'PageToday'
    
    def __str__(self):
        return str("PageToday <- Page detail: %s" % self.page_detail)

webmaster_area/forms.py
from webmaster_area.models import WebmasterAreaModel, AreaCategory
from buttons_constructor.models import ButtonsConstructorModel
from django import forms

class WebmasterAreaForm(forms.ModelForm):
    name_area = forms.CharField(max_length=200)
    url = forms.URLField()
    NORMAL = 'NORM'
    ADULT = 'ADUL'
    AD_TYPES_CHOICES=(
        (NORMAL,'Нормальный'),
        (ADULT,'Для взрослых'),
    )
    ad_type = forms.ChoiceField(choices=AD_TYPES_CHOICES, required=True, initial=NORMAL)
    area_cat_list = AreaCategory.objects.all()
    AREA_CAT_DEFAULT = ''
    for a in area_cat_list:
        if not a.name in AREA_CAT_DEFAULT:
            AREA_CAT_DEFAULT += a.name + ','
    AREA_CAT_DEFAULT = AREA_CAT_DEFAULT[:-1]
    area_category = forms.CharField(max_length=600, initial=AREA_CAT_DEFAULT)
    #def __init__(self, user, *args, **kwargs):
    def __init__(self, *args, **kwargs):
        super(WebmasterAreaForm, self).__init__(*args, **kwargs)
        #self.fields['buttons_constructor'] = ButtonsConstructorModel.objects.filter(cabinet_webmaster=user.cabinet_webmaster).order_by('-pk')[0]
    class Meta:
        model = WebmasterAreaModel
        fields = ('name_area', 'url', 'area_category', 'ad_type')

templates/webmaster_area/detail-advert.html
  {% load staticfiles %}
<!DOCTYPE html>
 <html lang="en" class="sHeight-100p">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ page.title }}</title>

    <link href="{% static "sharewall-template/css/header.css" %}" rel="stylesheet"> 
    <link href="{% static "sharewall-template/css/media-queries.css" %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static "sharewall-template/css/highslide.css" %}"/>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> 
  </head>
  <body class="sWidth-100p sHeight-100p sOverHidden-X">
    <div class="sWrapper">
        <div class="sHeight-Auto">
            <div class="sContainer sMargin-Auto" style="width:100%;">
                <div class="sListConstructors" style="padding-bottom:0px">
                    <div id="highChartsSocial" style="padding-bottom: 40px; min-width: 310px; height: 400px; margin: 0 auto"></div>
                </div>

                <div class="sTableAreas sTextAlign-C">
                    <div class="sTableAreasFieldName">
                        <div class="sTableAreasField s735Hide" style="width:162px;text-align:center;"><span style="padding:0 20px 0 20px; text-align:center;"></span>
                        </div>
                        <div class="sTableAreasField" style="width:110px;text-align:center;"><span style="padding:0 20px 0 20px; text-align:center;">Показы</span>
                        </div>
                        <div class="sTableAreasField" style="width:100px;text-align:center;"><span style="padding:0 20px 0 20px; text-align:center;">Клики</span>
                        </div>
                        <div class="sTableAreasField" style="width:120px;text-align:center;"><span style="padding:0 20px 0 20px; text-align:center;">Заработок</span>
                        </div>
                    </div>
                      
                    <div class="sTableAreasCell">
                        <div class="sTableAreasField s735Hide" style="width:162px;text-align:center;"><span style="padding:0 20px 0 20px; text-align:center; color:#1693d5;">Заработок</span>
                        </div>
                        <div class="sTableAreasField" style="width:110px;text-align:center;"><span style="padding:0 20px 0 20px; text-align:center;">{{ statistic.shows }}</span>
                        </div>
                        <div class="sTableAreasField" style="width:100px;text-align:center;"><span style="padding:0 20px 0 20px; text-align:center;">{{ statistic.clicks }}</span>
                        </div>
                        <div class="sTableAreasField" style="width:120px;text-align:center;"><span style="padding:0 20px 0 20px; text-align:center;">{{ statistic.money }}</span>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <script src="{% static "sharewall-template/js/highcharts.js" %}"></script>
    <script src="{% static "sharewall-template/js/exporting.js" %}"></script>
    <!-- Additional files for the Highslide popup effect -->
    <script src="{% static "sharewall-template/js/highslide-full.min.js" %}"></script>
    <script src="{% static "sharewall-template/js/highslide.config.js" %}" charset="utf-8"></script>
    <script>
        $(function () {
            $('#highChartsSocial').highcharts({
                title: {
                    text: '',
                    x: -20 
                },
                subtitle: {
                    text: '',
                    x: -20
                },
                xAxis: {
                  categories: {{ dates|safe }}
                },
                yAxis: {
                    title: {
                        text: ''
                    },
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                //tooltip: {
                //    valueSuffix: ' просмотров'
                //},
                legend: {
                    layout: 'horizontal',
                    //align: 'top',
                    x: -20,
                    verticalAlign: 'top',
                    borderWidth: 0
                },
                series: [
                {
                    name: 'Показы',
                    data: {{ shows }}
                },
                {
                    name: 'Клики',
                    data: {{ clicks }}
                }, 
                {
                    name: 'Заработок',
                    data: {{ money }}
                }
                ]
            });
            $('.highcharts-button').hide();
            $('svg > text:last-of-type').hide();

            window.parent.$('.sListConstructors > span.sTabs.sActive').click();//!important

            window.parent.$('input#inputDate').val("{{ dates_range_start|safe }} - {{ dates_range_end|safe }}");
            window.parent.setDatePicker("{{ dates_range_start|safe }}", "{{ dates_range_end|safe }}");
            //window.parent.$('div.sBusyOverlay').hide();
        });
    </script>
  </body>
</html>

templates/webmaster_area/faq.html
  {% extends "skeleton.html" %}

  {% block title %}{{ page.title }}{% endblock %}

	{% block content %}

  <div class="sContent-PB">
      <div class="sContainer sMargin-Auto">

          <div class="sH1Wrapper">
              <h1 class="sH1 sFloat-L">{{ page.header }}</h1>
              <div class="sClear-Both"></div>
          </div>        
          <div class="sLine"></div>

          {% for f in faq %}
          <div style="margin-top:20px;">
              <div class="sFaqHeader">
                <span data-image></span>
                <span data-question>{{ f.header }}</span>
              </div>
              
              <div class="sFaqBody">
                <p>{{ f.text }}</p>
              </div>
          </div>
          {% endfor %}
      
          <div style="height:50px"></div>    
      </div>
  </div>

	{% endblock %}

  {% block footer_script %}

        <script>
          $(function(){
             $('.sFaqHeader').click(function(){
                $(this).next('.sFaqBody').toggle(); 
             }); 
          });
        </script>

  {% endblock %}

templates/webmaster_area/index.html
  {% extends "skeleton.html" %}

  {% block custom_style %}

    <style>
      .sAlertMessageWrapper{
        color: #fff;
        background-color: #2fabf6;
      } 
    </style>

  {% endblock %}   

  {% block title %}{{ page.title }}{% endblock %}

	{% block content %}

  {% if user.is_staff and not request.session.profile %}

    <div class="sAlertMessageWrapper"></div>

    <div class="sPopupWrapper">

      <div class="sPopupWrapper-Modal" data-modal="cat">
        <p>Категория</p> 
        <input required type="text" name="catname" placeholder="Название категории" value=""/><br/>
        <span class="sBlockLink sBlockLink-Blue" data-modal="addcat">Добавить</span>
        <span class="sBlockLink sBlockLink-Red" data-modal="delcat">Удалить</span>
        <span data-modal="close"></span>
      </div> 

    </div>
  {% endif %}

  <div class="sContent-PB">
      <div class="sContainer sMargin-Auto">

          <div class="sH1Wrapper">
              <h1 class="sH1 sFloat-L">{{ page.header }}</h1>
              <span class="sAdd-Circle"></span>
              {% if user.is_staff and not request.session.profile %}
                <span class="sBlockLink sBlockLink-Blue sDisplay-Block" data-event="cat">Добавить/удалить категории</span>
              {% endif %}
              <div class="sClear-Both"></div>
          </div>        
          <div class="sTableAreas s936TextAlign-C">
              <div class="sTableAreasFieldName">
                  <div class="sTableAreasField s1200Width-5P"><span>ID</span>
                  </div>
                  <div class="sTableAreasField s1200Width-10P"><span>Название</span>
                  </div>
                  <div class="sTableAreasField s1200Width-15P"><span>URL</span>
                  </div>
                  <div class="sTableAreasField s1200Width-40P"><span>Категории</span>
                  </div>
                  <div class="sTableAreasField s1200Width-15P"><span>Типы рекламы</span>
                  </div>
                  <div class="sTableAreasField s1200Width-10P"><span>Действия</span>
                  </div>
              </div>
              {% for a in areas %}
              <div class="sTableAreasCell">
                  <div class="sTableAreasField s1200Width-5P"><span>{{ a.pk }}</span>
                  </div>
                  <div class="sTableAreasField s1200Width-10P"><a>{{ a.name_area }}</a>
                  </div>
                  <div class="sTableAreasField s1200Width-15P"><a target="_blank" href="//{{ a.url }}">{{ a.url }}</a>
                  </div>
                  <div class="sTableAreasField s1200Width-40P"><span>{{ a.area_category }}</span>
                  </div>
                  <div class="sTableAreasField s1200Width-15P"><span>{{ a.get_ad_type_display }}</span>
                  </div>
                  <div class="sTableAreasField s1200Width-10P">
                      <span title="Редактировать" class="sAreaEdit" onclick="eventUpdate(this)"></span>
                      <a title="Удалить" href="/webmaster-area/delete/{{ a.pk }}/" class="sAreaDelete"></a>
                  </div>
              </div>
              {% endfor %}
          </div>         
          <form id="create_form" style="display:none; opacity:0;" method="post" action="/webmaster-area/create/">
              {% csrf_token %}
              <input type="submit" />
          </form>
          <div class="sAddAreaModal" data-mode="create">
              <div class="sH1">Добавление площадки</div>
              <div class="sAddAreaWrapper">  
                  <div class="sFloat-L s1030MarginLeft-75PX s935Margin-0">
                      <label for="add_name_area">Название</label>
                      <label for="add_url">URL</label> 
                      <label for="add_category">Категории</label>
                      <label for="add_ad_type">Типы рекламы</label>
                  </div>
                  <div class="sFloat-L" style="padding-top:0px;">  
                       <div id="fixMac" style="height:58px; text-align:center;"></div>
                       <div>                       
                            <input form="create_form" id="add_name_area" type="text" pattern="[^?#%]+$" name="name_area" value="" maxlength="200" required>
                        </div> 
                        <div>        
                            <input form="create_form" id="add_url" placeholder="http://" type="url" name="url" value="" required>
                        </div> 
                        <div>                           
                          <select form="create_form" id="add_category" name="area_category" size="{{ area_category.count }}" multiple required>
                                {% for a in area_category %}
                                <option value="{{ a.pk }}">{{ a.name }}</option>
                                {% endfor %}
                            </select>
                        </div> 
                        <div>                           
                            <select form="create_form" id="add_ad_type" name="ad_type" required style="padding-left: 5px;">
                                <option value="NORM">Нормальный</option>
                                <option value="ADUL">Для взрослых</option>
                            </select>
                        </div> 
                  </div>                
                  <div class="sClear-Both"></div>
                  <span onclick="formSubmit()" class="sAddAreaSubmit sMargin-Auto"></span>
              </div>
          </div>

      </div>
  </div>
	{% endblock %}

  {% block footer_script %}

        <script>

          $('form').submit(function(e){
            console.log('submit event');

            $.ajax({
              url: $('form').attr('action'), 
              type: "POST", 
              data: $('form').serialize(), 
              cache: false,
              success: function(response, status, jqXHR) { 

                console.log(response.answer);

                $('#fixMac').text(response.answer);
                
                console.log($('#fixMac').text());

                $('.sAlertMessageWrapper').text(response.answer).fadeIn(500);

                window.setTimeout(function(){
                  $('.sAlertMessageWrapper').text('').fadeOut(500);
                    if(response.code == 'OK'){
                      $('#fixMac').text('');

                      (location.search.split('?next=').length > 1 ? window.location = location.search.split('?next=')[1] : window.location = '/webmaster-area/');
                    }
                },2000);

              }
            });

            return false;
          });

            function formSubmit(){
                $('form input[type="submit"]').click();
            }

            function eventUpdate(e){
                $this = $(e);
                $parent = $this.closest('.sTableAreasCell');
                $pk = $parent.find('.sTableAreasField:nth-child(1)').find('span').text();
                $name_area = $parent.find('.sTableAreasField:nth-child(2)').find('a').text();
                $url = $parent.find('.sTableAreasField:nth-child(3)').find('a').text();
                $area_category = $parent.find('.sTableAreasField:nth-child(4)').find('span').text();
                $ad_type = $parent.find('.sTableAreasField:nth-child(5)').find('span').text();

                $modal = $('div.sAddAreaModal'); 
                $modal.find('div.sH1').text('Изменение площадки №'+$pk);
                $modal.find('input[name="name_area"]').val($name_area).prop('disabled', true);
                $modal.find('input[name="url"]').val('http://'+$url).prop('disabled', true);

                $('select[name="area_category"]').find('option').prop('selected', false);
                $area_category.split(',').forEach(function(v,i){
                  $('select[name="area_category"]').find('option:contains('+v+')').prop('selected', true);
                });

                $('select[name="ad_type"]').find('option').prop('selected', false);
                $ad_type.split(',').forEach(function(v,i){
                  $('select[name="ad_type"]').find('option:contains('+v+')').prop('selected', true);
                });

                $('form#create_form').attr('action','/webmaster-area/update/'+$pk+'/')

                if($modal.data('mode') == $pk){ $modal.toggle(); }
                else { $modal.data('mode', $pk).show(); }
            }

            $(function(){

                $('div.sH1Wrapper span.sAdd-Circle').click(function(){ 
                  $modal = $('div.sAddAreaModal'); 
                  $modal.find('div.sH1').text('Добавление площадки');
                  $modal.find('input[name="name_area"]').val('').prop('disabled', false);
                  $modal.find('input[name="url"]').val('').prop('disabled', false);
                  $('select[name="area_category"]').find('option').prop('selected', false);
                  $('select[name="ad_type"]').find('option').prop('selected', false);

                  $('form#create_form').attr('action','/webmaster-area/create/')

                  if($modal.data('mode') == 'create'){ $modal.toggle(); }
                  else { $modal.data('mode', 'create').show(); }
                });

                $('.sAddAreaWrapper > div:nth-child(1) > label:nth-child(4)').css('padding-top', $('select#add_category').attr('size') * 30);

                if(location.search.indexOf('?create') != -1){
                    $('div.sH1Wrapper span.sAdd-Circle').click(); 
                }

                {% if user.is_staff and not request.session.profile %}

                   $('[data-event]').click(function(){
                       $('.sPopupWrapper').show();
                       var event = $(this).data('event');
                       $('[data-modal="'+event+'"]').show();
                   }); 
                    
                   $('[data-modal="close"]').click(function(){
                      $('.sPopupWrapper-Modal').hide(); 
                      $('.sPopupWrapper').hide();
                   });  

                   $('[data-modal="addcat"]').click(function(){
                       var name = $('input[name="catname"]').val();

                       if(name){
                       $.ajax({ 
                          url: "{% url "webmaster-area-add-category" %}", 
                          type: "POST", 
                          data: {"name": name}, 
                          success: function(response, status, jqXHR) { 
                              console.log(response);

                              $('[data-modal="close"]').click();

                              if(response == 'OK'){
                                  window.location.reload();
                              }else{
                                  $('.sAlertMessageWrapper').text(response).fadeIn('slow');
                                  window.setTimeout(function(){
                                    $('.sAlertMessageWrapper').text('').fadeOut('slow');
                                  },2000);
                              }

                          }
                      });
                       }else{
                            $('.sAlertMessageWrapper').css('z-index','2').text("Ошибка! Введите название!").fadeIn('slow');
                            window.setTimeout(function(){
                              $('.sAlertMessageWrapper').css('z-index','1').text('').fadeOut('slow');
                            },2000); 
                         }

                   }); 

                   $('[data-modal="delcat"]').click(function(){
                       var name = $('input[name="catname"]').val();

                       if(name){
                       $.ajax({ 
                          url: "{% url "webmaster-area-delete-category" %}", 
                          type: "POST", 
                          data: {"name": name}, 
                          success: function(response, status, jqXHR) { 
                              console.log(response);

                              $('[data-modal="close"]').click();

                              if(response == 'OK'){
                                  window.location.reload();
                              }else{
                                  $('.sAlertMessageWrapper').text(response).fadeIn('slow');
                                  window.setTimeout(function(){
                                    $('.sAlertMessageWrapper').text('').fadeOut('slow');
                                  },2000);
                              }

                          }
                      });
                        }else{
                            $('.sAlertMessageWrapper').css('z-index','2').text("Ошибка! Введите название!").fadeIn('slow');
                            window.setTimeout(function(){
                              $('.sAlertMessageWrapper').css('z-index','1').text('').fadeOut('slow');
                            },2000); 
                         }

                   }); 

                {% endif %}

            });            
          
        </script>

  {% endblock %}

templates/webmaster_area/skeleton.html
{% extends "skeleton.html" %}